/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package statetablereader;

import java.awt.Color;
import javax.swing.JButton;
import statetablereader.utils.StateTable;

/**
 *
 * @author Harish
 */
public class StateTableViewerForm extends javax.swing.JFrame {

    /**
     * Creates new form StateTableViewerForm
     */
    public StateTableViewerForm() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StateTableViewerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StateTableViewerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StateTableViewerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StateTableViewerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
//    public StateTableViewerForm(StateTable st)
//    {
//        initComponents();
//        JButton a = new JButton();
//        a.setText("Helloworld");
//        a.setSize(90, 30);
//        a.setBackground(Color.GREEN);
//        //a.setBorder(null);
//        a.setLocation(1800, 300);
//        jScrollPane1.add(a);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("State Table Viewer");
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public void adjustScroll()
    {
        
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
